-- Read-only column definition batch 3, containing 130 expected columns.
WITH
expected_columns(table_name,column_name,column_type,notnull_flag,default_value,pk) AS (VALUES
('job_materials','invoice_number','TEXT',0,NULL,0),
('job_materials','invoice_date','TEXT',0,NULL,0),
('job_materials','invoice_file_id','TEXT',0,NULL,0),
('job_materials','description','TEXT',1,NULL,0),
('job_materials','supplier_sku','TEXT',0,NULL,0),
('job_materials','quantity','REAL',1,'1',0),
('job_materials','unit_code','TEXT',0,NULL,0),
('job_materials','unit_cost_ex_gst','REAL',1,'0',0),
('job_materials','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_materials','billable_to_customer','INTEGER',1,'1',0),
('job_materials','customer_markup_percent','REAL',1,'30',0),
('job_materials','material_status','TEXT',1,'''normal''',0),
('job_materials','supplier_invoice_inbox_id','TEXT',0,NULL,0),
('job_supplier_pricing','job_id','INTEGER',0,NULL,1),
('job_supplier_pricing','data_json','TEXT',1,NULL,0),
('job_supplier_pricing','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_work_logs','id','TEXT',0,NULL,1),
('job_work_logs','job_id','INTEGER',1,NULL,0),
('job_work_logs','work_date','TEXT',1,NULL,0),
('job_work_logs','hours','REAL',1,NULL,0),
('job_work_logs','supervisor','TEXT',0,NULL,0),
('job_work_logs','supervision_type','TEXT',1,NULL,0),
('job_work_logs','competency','TEXT',1,NULL,0),
('job_work_logs','work_completed','TEXT',1,NULL,0),
('job_work_logs','tests_results','TEXT',0,NULL,0),
('job_work_logs','issues_notes','TEXT',0,NULL,0),
('job_work_logs','supervisor_notes','TEXT',0,NULL,0),
('job_work_logs','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_work_logs','start_time','TEXT',0,NULL,0),
('job_work_logs','finish_time','TEXT',0,NULL,0),
('job_work_logs','materials_used','TEXT',0,NULL,0),
('job_work_logs','certification_status','TEXT',0,NULL,0),
('job_work_logs','work_dates','TEXT',0,NULL,0),
('job_work_logs','days','REAL',1,'1',0),
('jobs','id','INTEGER',0,NULL,1),
('jobs','enquiry_id','INTEGER',1,NULL,0),
('jobs','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('jobs','job_status','TEXT',1,'''new_enquiry''',0),
('jobs','next_action','TEXT',0,NULL,0),
('jobs','next_action_date','TEXT',0,NULL,0),
('jobs','assigned_to','TEXT',0,NULL,0),
('jobs','quote_amount','REAL',0,NULL,0),
('jobs','quote_status','TEXT',0,'''not_started''',0),
('jobs','accepted_at','TEXT',0,NULL,0),
('jobs','opensolar_project_id','TEXT',0,NULL,0),
('jobs','opensolar_project_url','TEXT',0,NULL,0),
('jobs','opensolar_status','TEXT',0,'''not_created''',0),
('jobs','system_size_kw','REAL',0,NULL,0),
('jobs','inverter','TEXT',0,NULL,0),
('jobs','battery','TEXT',0,NULL,0),
('jobs','proposal_value','REAL',0,NULL,0),
('jobs','proposal_sent_at','TEXT',0,NULL,0),
('jobs','icp','TEXT',0,NULL,0),
('jobs','vector_dg_status','TEXT',0,'''not_started''',0),
('jobs','vector_dg_submitted_at','TEXT',0,NULL,0),
('jobs','vector_dg_reference','TEXT',0,NULL,0),
('jobs','vector_dg_approved_at','TEXT',0,NULL,0),
('jobs','export_limit_kw','REAL',0,NULL,0),
('jobs','retailer','TEXT',0,NULL,0),
('jobs','retailer_plan','TEXT',0,NULL,0),
('jobs','import_rate_cents','REAL',0,NULL,0),
('jobs','export_rate_cents','REAL',0,NULL,0),
('jobs','daily_fixed_charge','REAL',0,NULL,0),
('jobs','tariff_check_status','TEXT',0,'''not_checked''',0),
('jobs','recommended_retailer','TEXT',0,NULL,0),
('jobs','recommended_plan','TEXT',0,NULL,0),
('jobs','retailer_status','TEXT',0,'''not_started''',0),
('jobs','retailer_contacted_at','TEXT',0,NULL,0),
('jobs','meter_status','TEXT',0,'''not_checked''',0),
('jobs','export_confirmed','INTEGER',0,'0',0),
('jobs','finance_type','TEXT',0,'''unknown''',0),
('jobs','finance_provider','TEXT',0,NULL,0),
('jobs','finance_status','TEXT',0,'''not_applicable''',0),
('jobs','deposit_required','REAL',0,NULL,0),
('jobs','deposit_status','TEXT',0,'''not_requested''',0),
('jobs','deposit_received','REAL',0,NULL,0),
('jobs','deposit_received_at','TEXT',0,NULL,0),
('jobs','materials_status','TEXT',0,'''not_ordered''',0),
('jobs','materials_cost','REAL',0,NULL,0),
('jobs','materials_ordered_at','TEXT',0,NULL,0),
('jobs','materials_received_at','TEXT',0,NULL,0),
('jobs','supplier','TEXT',0,NULL,0),
('jobs','install_status','TEXT',0,'''not_scheduled''',0),
('jobs','install_date','TEXT',0,NULL,0),
('jobs','install_completed_at','TEXT',0,NULL,0),
('jobs','trainee_hours','REAL',0,NULL,0),
('jobs','trainee_work_notes','TEXT',0,NULL,0),
('jobs','install_photos_status','TEXT',0,'''not_uploaded''',0),
('jobs','test_sheet_status','TEXT',0,'''not_completed''',0),
('jobs','supervisor','TEXT',0,'''Ben''',0),
('jobs','supervision_status','TEXT',0,'''not_started''',0),
('jobs','supervisor_approval_status','TEXT',0,'''not_approved''',0),
('jobs','inspection_status','TEXT',0,'''not_required''',0),
('jobs','inspector','TEXT',0,NULL,0),
('jobs','inspection_date','TEXT',0,NULL,0),
('jobs','coc_status','TEXT',0,'''not_issued''',0),
('jobs','coc_number','TEXT',0,NULL,0),
('jobs','coc_issued_at','TEXT',0,NULL,0),
('jobs','final_payment_status','TEXT',0,'''not_due''',0),
('jobs','final_payment_received_at','TEXT',0,NULL,0),
('jobs','job_type','TEXT',1,'''solar''',0),
('jobs','supplier_reference','TEXT',0,NULL,0),
('site_visits','job_id','INTEGER',0,NULL,1),
('site_visits','data_json','TEXT',1,NULL,0),
('site_visits','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('supplier_products','id','TEXT',0,NULL,1),
('supplier_products','supplier_id','TEXT',1,NULL,0),
('supplier_products','supplier_sku','TEXT',1,NULL,0),
('supplier_products','description','TEXT',1,NULL,0),
('supplier_products','unit_code','TEXT',0,NULL,0),
('supplier_products','category_code','TEXT',0,NULL,0),
('supplier_products','barcode','TEXT',0,NULL,0),
('supplier_products','list_price','REAL',0,NULL,0),
('supplier_products','buy_price','REAL',0,NULL,0),
('supplier_products','gst_treatment','TEXT',1,'''exclusive''',0),
('supplier_products','brand','TEXT',0,NULL,0),
('supplier_products','manufacturer_sku','TEXT',0,NULL,0),
('supplier_products','price_class','TEXT',0,NULL,0),
('supplier_products','source_price_date','TEXT',0,NULL,0),
('supplier_products','last_imported_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('supplier_products','active','INTEGER',1,'1',0),
('suppliers','id','TEXT',0,NULL,1),
('suppliers','name','TEXT',1,NULL,0),
('suppliers','active','INTEGER',1,'1',0),
('suppliers','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('suppliers','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('suppliers','is_default','INTEGER',1,'0',0),
('system_designs','job_id','INTEGER',0,NULL,1),
('system_designs','data_json','TEXT',1,NULL,0),
('system_designs','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0)
),
actual_columns(table_name,column_name,column_type,notnull_flag,default_value,pk) AS (
 SELECT s.name,p.name,upper(coalesce(p.type,'')),p."notnull",p.dflt_value,p.pk
 FROM sqlite_schema AS s JOIN pragma_table_info(s.name) AS p
 WHERE s.type='table' AND s.sql IS NOT NULL
  AND s.name NOT LIKE 'sqlite_%' AND substr(s.name,1,4)<>'_cf_' AND s.name<>'d1_migrations'
)
SELECT 'JOBHUB_VERIFY_OK:columns-03' AS result
WHERE NOT EXISTS(SELECT 1 FROM expected_columns e WHERE NOT EXISTS(
 SELECT 1 FROM actual_columns a WHERE a.table_name=e.table_name AND a.column_name=e.column_name
  AND upper(a.column_type)=e.column_type AND a.notnull_flag=e.notnull_flag
  AND a.default_value IS e.default_value AND a.pk=e.pk
))
UNION ALL
SELECT 'MISSING_OR_MISMATCHED_COLUMN:'||e.table_name||'.'||e.column_name
FROM expected_columns e WHERE NOT EXISTS(
 SELECT 1 FROM actual_columns a WHERE a.table_name=e.table_name AND a.column_name=e.column_name
  AND upper(a.column_type)=e.column_type AND a.notnull_flag=e.notnull_flag
  AND a.default_value IS e.default_value AND a.pk=e.pk
);

