-- Read-only exact structural check for the post-0018 Job Hub application schema.
-- Excludes SQLite/Cloudflare internals and Wrangler's d1_migrations ledger.
WITH
expected_tables(name) AS (VALUES
('assessments'),
('bookkeeping_accounts'),
('bookkeeping_audit_events'),
('bookkeeping_bank_accounts'),
('bookkeeping_bank_feed_audit'),
('bookkeeping_bank_feed_imports'),
('bookkeeping_bank_feed_transactions'),
('bookkeeping_books'),
('bookkeeping_document_links'),
('bookkeeping_export_mappings'),
('bookkeeping_fixed_assets'),
('bookkeeping_job_books'),
('bookkeeping_journal_lines'),
('bookkeeping_journals'),
('bookkeeping_opening_balances'),
('bookkeeping_payment_allocations'),
('bookkeeping_reconciliation_matches'),
('bookkeeping_reconciliation_reviews'),
('bookkeeping_supplier_inbox_addresses'),
('bookkeeping_supplier_invoice_events'),
('bookkeeping_supplier_invoice_inbox'),
('bookkeeping_tax_accounts'),
('bookkeeping_tax_adjustments'),
('bookkeeping_tax_events'),
('bookkeeping_transactions'),
('catalogue_imports'),
('costing_lines'),
('costing_options'),
('customer_invoice_versions'),
('customer_quote_versions'),
('email_logs'),
('enquiries'),
('general_job_details'),
('job_files'),
('job_materials'),
('job_supplier_pricing'),
('job_work_logs'),
('jobs'),
('site_visits'),
('supplier_products'),
('suppliers'),
('system_designs')
),
expected_columns(table_name, column_name, column_type, notnull_flag, default_value, pk) AS (VALUES
('assessments','id','INTEGER',0,NULL,1),
('assessments','job_id','INTEGER',1,NULL,0),
('assessments','solar_kw','REAL',0,NULL,0),
('assessments','panel_count','INTEGER',0,NULL,0),
('assessments','inverter','TEXT',0,NULL,0),
('assessments','estimated_generation_kwh','INTEGER',0,NULL,0),
('assessments','hot_water_strategy','TEXT',0,NULL,0),
('assessments','smart_controls','TEXT',0,NULL,0),
('assessments','battery_option','TEXT',0,NULL,0),
('assessments','battery_kwh','REAL',0,NULL,0),
('assessments','tariff_recommendation','TEXT',0,NULL,0),
('assessments','site_notes','TEXT',0,NULL,0),
('assessments','recommendation','TEXT',0,NULL,0),
('assessments','updated_at','TEXT',0,'CURRENT_TIMESTAMP',0),
('assessments','panel_wattage','INTEGER',0,'445',0),
('assessments','roof_orientation','TEXT',0,NULL,0),
('assessments','battery_reason','TEXT',0,NULL,0),
('assessments','current_retailer','TEXT',0,NULL,0),
('assessments','import_rate','REAL',0,NULL,0),
('assessments','export_rate','REAL',0,NULL,0),
('assessments','controlled_hot_water','TEXT',0,NULL,0),
('assessments','recommended_tariff','TEXT',0,NULL,0),
('assessments','tariff_notes','TEXT',0,NULL,0),
('bookkeeping_accounts','id','TEXT',0,NULL,1),
('bookkeeping_accounts','book_id','TEXT',1,NULL,0),
('bookkeeping_accounts','code','TEXT',1,NULL,0),
('bookkeeping_accounts','name','TEXT',1,NULL,0),
('bookkeeping_accounts','account_type','TEXT',1,NULL,0),
('bookkeeping_accounts','tax_code','TEXT',1,'''no_gst''',0),
('bookkeeping_accounts','is_control','INTEGER',1,'0',0),
('bookkeeping_accounts','is_active','INTEGER',1,'1',0),
('bookkeeping_accounts','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_audit_events','id','TEXT',0,NULL,1),
('bookkeeping_audit_events','book_id','TEXT',1,NULL,0),
('bookkeeping_audit_events','transaction_id','TEXT',0,NULL,0),
('bookkeeping_audit_events','entity_type','TEXT',1,NULL,0),
('bookkeeping_audit_events','entity_id','TEXT',1,NULL,0),
('bookkeeping_audit_events','action','TEXT',1,NULL,0),
('bookkeeping_audit_events','actor','TEXT',0,NULL,0),
('bookkeeping_audit_events','event_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_audit_events','before_json','TEXT',0,NULL,0),
('bookkeeping_audit_events','after_json','TEXT',0,NULL,0),
('bookkeeping_bank_accounts','id','TEXT',0,NULL,1),
('bookkeeping_bank_accounts','book_id','TEXT',1,NULL,0),
('bookkeeping_bank_accounts','ledger_account_id','TEXT',1,NULL,0),
('bookkeeping_bank_accounts','account_name','TEXT',1,NULL,0),
('bookkeeping_bank_accounts','provider_code','TEXT',1,'''manual_import''',0),
('bookkeeping_bank_accounts','external_account_id','TEXT',0,NULL,0),
('bookkeeping_bank_accounts','account_number_masked','TEXT',0,NULL,0),
('bookkeeping_bank_accounts','currency','TEXT',1,'''NZD''',0),
('bookkeeping_bank_accounts','current_balance','REAL',0,NULL,0),
('bookkeeping_bank_accounts','balance_as_at','TEXT',0,NULL,0),
('bookkeeping_bank_accounts','active','INTEGER',1,'1',0),
('bookkeeping_bank_accounts','settings_json','TEXT',1,'''{}''',0),
('bookkeeping_bank_accounts','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_bank_accounts','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_bank_feed_audit','id','TEXT',0,NULL,1),
('bookkeeping_bank_feed_audit','book_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_audit','bank_transaction_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_audit','action','TEXT',1,NULL,0),
('bookkeeping_bank_feed_audit','actor','TEXT',0,NULL,0),
('bookkeeping_bank_feed_audit','details_json','TEXT',1,'''{}''',0),
('bookkeeping_bank_feed_audit','event_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_bank_feed_imports','id','TEXT',0,NULL,1),
('bookkeeping_bank_feed_imports','book_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_imports','bank_account_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_imports','source_type','TEXT',1,NULL,0),
('bookkeeping_bank_feed_imports','source_batch_id','TEXT',0,NULL,0),
('bookkeeping_bank_feed_imports','import_fingerprint','TEXT',1,NULL,0),
('bookkeeping_bank_feed_imports','source_filename','TEXT',0,NULL,0),
('bookkeeping_bank_feed_imports','row_count','INTEGER',1,'0',0),
('bookkeeping_bank_feed_imports','duplicate_count','INTEGER',1,'0',0),
('bookkeeping_bank_feed_imports','imported_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_bank_feed_imports','imported_by','TEXT',0,NULL,0),
('bookkeeping_bank_feed_imports','metadata_json','TEXT',1,'''{}''',0),
('bookkeeping_bank_feed_transactions','id','TEXT',0,NULL,1),
('bookkeeping_bank_feed_transactions','book_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_transactions','bank_account_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_transactions','import_id','TEXT',1,NULL,0),
('bookkeeping_bank_feed_transactions','external_transaction_id','TEXT',0,NULL,0),
('bookkeeping_bank_feed_transactions','transaction_date','TEXT',1,NULL,0),
('bookkeeping_bank_feed_transactions','direction','TEXT',1,NULL,0),
('bookkeeping_bank_feed_transactions','amount','REAL',1,NULL,0),
('bookkeeping_bank_feed_transactions','currency','TEXT',1,'''NZD''',0),
('bookkeeping_bank_feed_transactions','counterparty','TEXT',0,NULL,0),
('bookkeeping_bank_feed_transactions','reference','TEXT',0,NULL,0),
('bookkeeping_bank_feed_transactions','description','TEXT',1,'''''',0),
('bookkeeping_bank_feed_transactions','transaction_code','TEXT',0,NULL,0),
('bookkeeping_bank_feed_transactions','transaction_status','TEXT',1,'''needs_matching''',0),
('bookkeeping_bank_feed_transactions','reconciliation_status','TEXT',1,'''unreconciled''',0),
('bookkeeping_bank_feed_transactions','raw_json','TEXT',1,'''{}''',0),
('bookkeeping_bank_feed_transactions','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_books','id','TEXT',0,NULL,1),
('bookkeeping_books','name','TEXT',1,NULL,0),
('bookkeeping_books','legal_name','TEXT',0,NULL,0),
('bookkeeping_books','currency','TEXT',1,'''NZD''',0),
('bookkeeping_books','gst_registered','INTEGER',1,'0',0),
('bookkeeping_books','gst_number','TEXT',0,NULL,0),
('bookkeeping_books','gst_basis','TEXT',1,'''unconfigured''',0),
('bookkeeping_books','gst_rate','REAL',1,'0.15',0),
('bookkeeping_books','commencement_date','TEXT',0,NULL,0),
('bookkeeping_books','historical_label','TEXT',1,'''Historical / Hnry''',0),
('bookkeeping_books','company_tax_rate','REAL',1,'0.28',0),
('bookkeeping_books','company_tax_enabled','INTEGER',1,'0',0),
('bookkeeping_books','income_tax_method','TEXT',1,'''accounting_profit''',0),
('bookkeeping_books','payment_terms_days','INTEGER',1,'7',0),
('bookkeeping_books','invoice_prefix','TEXT',1,'''INV''',0),
('bookkeeping_books','next_invoice_number','INTEGER',1,'1',0),
('bookkeeping_books','settings_json','TEXT',1,'''{}''',0),
('bookkeeping_books','active','INTEGER',1,'1',0),
('bookkeeping_books','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_books','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_document_links','id','TEXT',0,NULL,1),
('bookkeeping_document_links','book_id','TEXT',1,NULL,0),
('bookkeeping_document_links','transaction_id','TEXT',1,NULL,0),
('bookkeeping_document_links','file_id','TEXT',1,NULL,0),
('bookkeeping_document_links','role','TEXT',1,'''supporting_document''',0),
('bookkeeping_document_links','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_export_mappings','id','TEXT',0,NULL,1),
('bookkeeping_export_mappings','book_id','TEXT',1,NULL,0),
('bookkeeping_export_mappings','export_type','TEXT',1,NULL,0),
('bookkeeping_export_mappings','mapping_name','TEXT',1,NULL,0),
('bookkeeping_export_mappings','field_mapping_json','TEXT',1,NULL,0),
('bookkeeping_export_mappings','is_default','INTEGER',1,'0',0),
('bookkeeping_export_mappings','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_fixed_assets','id','TEXT',0,NULL,1),
('bookkeeping_fixed_assets','book_id','TEXT',1,NULL,0),
('bookkeeping_fixed_assets','transaction_id','TEXT',0,NULL,0),
('bookkeeping_fixed_assets','asset_name','TEXT',1,NULL,0),
('bookkeeping_fixed_assets','asset_category','TEXT',1,NULL,0),
('bookkeeping_fixed_assets','acquired_date','TEXT',1,NULL,0),
('bookkeeping_fixed_assets','cost_ex_gst','REAL',1,'0',0),
('bookkeeping_fixed_assets','gst_amount','REAL',1,'0',0),
('bookkeeping_fixed_assets','gst_treatment','TEXT',1,'''no_gst''',0),
('bookkeeping_fixed_assets','useful_life_months','INTEGER',0,NULL,0),
('bookkeeping_fixed_assets','depreciation_method','TEXT',0,NULL,0),
('bookkeeping_fixed_assets','residual_value','REAL',1,'0',0),
('bookkeeping_fixed_assets','disposed_date','TEXT',0,NULL,0),
('bookkeeping_fixed_assets','disposal_amount','REAL',0,NULL,0),
('bookkeeping_fixed_assets','metadata_json','TEXT',1,'''{}''',0),
('bookkeeping_fixed_assets','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_job_books','job_id','INTEGER',0,NULL,1),
('bookkeeping_job_books','book_id','TEXT',1,NULL,0),
('bookkeeping_job_books','assigned_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_job_books','assigned_by','TEXT',0,NULL,0),
('bookkeeping_journal_lines','id','TEXT',0,NULL,1),
('bookkeeping_journal_lines','journal_id','TEXT',1,NULL,0),
('bookkeeping_journal_lines','account_id','TEXT',1,NULL,0),
('bookkeeping_journal_lines','description','TEXT',1,'''''',0),
('bookkeeping_journal_lines','debit','REAL',1,'0',0),
('bookkeeping_journal_lines','credit','REAL',1,'0',0),
('bookkeeping_journal_lines','ex_gst_amount','REAL',1,'0',0),
('bookkeeping_journal_lines','gst_amount','REAL',1,'0',0),
('bookkeeping_journal_lines','total_incl_gst','REAL',1,'0',0),
('bookkeeping_journal_lines','gst_treatment','TEXT',1,'''no_gst''',0),
('bookkeeping_journal_lines','contact_name','TEXT',0,NULL,0),
('bookkeeping_journal_lines','job_id','INTEGER',0,NULL,0),
('bookkeeping_journals','id','TEXT',0,NULL,1),
('bookkeeping_journals','book_id','TEXT',1,NULL,0),
('bookkeeping_journals','transaction_id','TEXT',0,NULL,0),
('bookkeeping_journals','journal_date','TEXT',1,NULL,0),
('bookkeeping_journals','reference_number','TEXT',0,NULL,0),
('bookkeeping_journals','description','TEXT',1,'''''',0),
('bookkeeping_journals','source','TEXT',1,'''manual''',0),
('bookkeeping_journals','posted','INTEGER',1,'0',0),
('bookkeeping_journals','reversed_by','TEXT',0,NULL,0),
('bookkeeping_journals','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_opening_balances','id','TEXT',0,NULL,1),
('bookkeeping_opening_balances','book_id','TEXT',1,NULL,0),
('bookkeeping_opening_balances','account_id','TEXT',1,NULL,0),
('bookkeeping_opening_balances','as_at_date','TEXT',1,NULL,0),
('bookkeeping_opening_balances','debit','REAL',1,'0',0),
('bookkeeping_opening_balances','credit','REAL',1,'0',0),
('bookkeeping_opening_balances','source_label','TEXT',1,'''Accountant supplied opening balance''',0),
('bookkeeping_opening_balances','reference_number','TEXT',0,NULL,0),
('bookkeeping_opening_balances','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_payment_allocations','id','TEXT',0,NULL,1),
('bookkeeping_payment_allocations','book_id','TEXT',1,NULL,0),
('bookkeeping_payment_allocations','payment_transaction_id','TEXT',1,NULL,0),
('bookkeeping_payment_allocations','invoice_transaction_id','TEXT',1,NULL,0),
('bookkeeping_payment_allocations','amount','REAL',1,NULL,0),
('bookkeeping_payment_allocations','allocated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_reconciliation_matches','id','TEXT',0,NULL,1),
('bookkeeping_reconciliation_matches','book_id','TEXT',1,NULL,0),
('bookkeeping_reconciliation_matches','bank_transaction_id','TEXT',1,NULL,0),
('bookkeeping_reconciliation_matches','payment_transaction_id','TEXT',1,NULL,0),
('bookkeeping_reconciliation_matches','target_transaction_id','TEXT',1,NULL,0),
('bookkeeping_reconciliation_matches','allocated_amount','REAL',1,NULL,0),
('bookkeeping_reconciliation_matches','match_method','TEXT',1,NULL,0),
('bookkeeping_reconciliation_matches','confidence_score','INTEGER',0,NULL,0),
('bookkeeping_reconciliation_matches','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_reconciliation_matches','created_by','TEXT',0,NULL,0),
('bookkeeping_reconciliation_reviews','id','TEXT',0,NULL,1),
('bookkeeping_reconciliation_reviews','book_id','TEXT',1,NULL,0),
('bookkeeping_reconciliation_reviews','bank_transaction_id','TEXT',1,NULL,0),
('bookkeeping_reconciliation_reviews','review_status','TEXT',1,'''needs_matching''',0),
('bookkeeping_reconciliation_reviews','suggested_matches_json','TEXT',1,'''[]''',0),
('bookkeeping_reconciliation_reviews','selected_transaction_id','TEXT',0,NULL,0),
('bookkeeping_reconciliation_reviews','confidence_score','INTEGER',0,NULL,0),
('bookkeeping_reconciliation_reviews','decision_reason','TEXT',0,NULL,0),
('bookkeeping_reconciliation_reviews','decided_by','TEXT',0,NULL,0),
('bookkeeping_reconciliation_reviews','decided_at','TEXT',0,NULL,0),
('bookkeeping_reconciliation_reviews','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_reconciliation_reviews','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_supplier_inbox_addresses','id','TEXT',0,NULL,1),
('bookkeeping_supplier_inbox_addresses','book_id','TEXT',1,NULL,0),
('bookkeeping_supplier_inbox_addresses','email_address','TEXT',1,NULL,0),
('bookkeeping_supplier_inbox_addresses','active','INTEGER',1,'1',0),
('bookkeeping_supplier_inbox_addresses','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_supplier_invoice_events','id','TEXT',0,NULL,1),
('bookkeeping_supplier_invoice_events','book_id','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_events','inbox_id','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_events','action','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_events','actor','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_events','details_json','TEXT',1,'''{}''',0),
('bookkeeping_supplier_invoice_events','event_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_supplier_invoice_inbox','id','TEXT',0,NULL,1),
('bookkeeping_supplier_invoice_inbox','book_id','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_inbox','source_type','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_inbox','sender_email','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','recipient_email','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','email_subject','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','email_message_id','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','received_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_supplier_invoice_inbox','attachment_name','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_inbox','content_type','TEXT',1,'''application/pdf''',0),
('bookkeeping_supplier_invoice_inbox','size_bytes','INTEGER',1,NULL,0),
('bookkeeping_supplier_invoice_inbox','content_sha256','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_inbox','storage_key','TEXT',1,NULL,0),
('bookkeeping_supplier_invoice_inbox','supplier_name','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','supplier_invoice_number','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','supplier_invoice_date','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','purchase_order_reference','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','subtotal_ex_gst','REAL',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','gst_amount','REAL',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','total_incl_gst','REAL',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','allowable_input_gst','REAL',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','extraction_status','TEXT',1,'''not_run''',0),
('bookkeeping_supplier_invoice_inbox','extraction_confidence','REAL',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','extraction_json','TEXT',1,'''{}''',0),
('bookkeeping_supplier_invoice_inbox','extraction_warnings_json','TEXT',1,'''[]''',0),
('bookkeeping_supplier_invoice_inbox','matching_status','TEXT',1,'''needs_matching''',0),
('bookkeeping_supplier_invoice_inbox','job_id','INTEGER',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','suggested_job_ids_json','TEXT',1,'''[]''',0),
('bookkeeping_supplier_invoice_inbox','duplicate_of_id','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','job_file_id','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','accounting_transaction_id','TEXT',0,NULL,0),
('bookkeeping_supplier_invoice_inbox','user_confirmed','INTEGER',1,'0',0),
('bookkeeping_supplier_invoice_inbox','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_supplier_invoice_inbox','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_tax_accounts','id','TEXT',0,NULL,1),
('bookkeeping_tax_accounts','book_id','TEXT',1,NULL,0),
('bookkeeping_tax_accounts','tax_type','TEXT',1,NULL,0),
('bookkeeping_tax_accounts','bank_account_name','TEXT',1,NULL,0),
('bookkeeping_tax_accounts','current_balance','REAL',1,'0',0),
('bookkeeping_tax_accounts','as_at_date','TEXT',0,NULL,0),
('bookkeeping_tax_accounts','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_tax_adjustments','id','TEXT',0,NULL,1),
('bookkeeping_tax_adjustments','book_id','TEXT',1,NULL,0),
('bookkeeping_tax_adjustments','tax_type','TEXT',1,NULL,0),
('bookkeeping_tax_adjustments','effective_date','TEXT',1,NULL,0),
('bookkeeping_tax_adjustments','amount','REAL',1,NULL,0),
('bookkeeping_tax_adjustments','reason','TEXT',1,NULL,0),
('bookkeeping_tax_adjustments','accountant_adjusted','INTEGER',1,'0',0),
('bookkeeping_tax_adjustments','reference_number','TEXT',0,NULL,0),
('bookkeeping_tax_adjustments','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_tax_events','id','TEXT',0,NULL,1),
('bookkeeping_tax_events','book_id','TEXT',1,NULL,0),
('bookkeeping_tax_events','tax_type','TEXT',1,NULL,0),
('bookkeeping_tax_events','event_type','TEXT',1,NULL,0),
('bookkeeping_tax_events','transaction_id','TEXT',0,NULL,0),
('bookkeeping_tax_events','event_date','TEXT',1,NULL,0),
('bookkeeping_tax_events','due_date','TEXT',0,NULL,0),
('bookkeeping_tax_events','reference_number','TEXT',0,NULL,0),
('bookkeeping_tax_events','description','TEXT',1,'''''',0),
('bookkeeping_tax_events','amount','REAL',1,NULL,0),
('bookkeeping_tax_events','metadata_json','TEXT',1,'''{}''',0),
('bookkeeping_tax_events','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_transactions','id','TEXT',0,NULL,1),
('bookkeeping_transactions','book_id','TEXT',1,NULL,0),
('bookkeeping_transactions','job_id','INTEGER',0,NULL,0),
('bookkeeping_transactions','kind','TEXT',1,NULL,0),
('bookkeeping_transactions','transaction_date','TEXT',1,NULL,0),
('bookkeeping_transactions','due_date','TEXT',0,NULL,0),
('bookkeeping_transactions','reference_number','TEXT',0,NULL,0),
('bookkeeping_transactions','contact_name','TEXT',0,NULL,0),
('bookkeeping_transactions','contact_id','TEXT',0,NULL,0),
('bookkeeping_transactions','description','TEXT',1,'''''',0),
('bookkeeping_transactions','account_id','TEXT',0,NULL,0),
('bookkeeping_transactions','status','TEXT',1,'''unpaid''',0),
('bookkeeping_transactions','payment_method','TEXT',0,NULL,0),
('bookkeeping_transactions','payment_reference','TEXT',0,NULL,0),
('bookkeeping_transactions','reconciliation_status','TEXT',1,'''unreconciled''',0),
('bookkeeping_transactions','gst_treatment','TEXT',1,'''no_gst''',0),
('bookkeeping_transactions','ex_gst_amount','REAL',1,'0',0),
('bookkeeping_transactions','gst_amount','REAL',1,'0',0),
('bookkeeping_transactions','total_incl_gst','REAL',1,'0',0),
('bookkeeping_transactions','historical','INTEGER',1,'0',0),
('bookkeeping_transactions','source_type','TEXT',0,NULL,0),
('bookkeeping_transactions','source_id','TEXT',0,NULL,0),
('bookkeeping_transactions','supporting_file_id','TEXT',0,NULL,0),
('bookkeeping_transactions','metadata_json','TEXT',1,'''{}''',0),
('bookkeeping_transactions','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_transactions','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('bookkeeping_transactions','allowable_input_gst','REAL',1,'0',0),
('catalogue_imports','id','TEXT',0,NULL,1),
('catalogue_imports','supplier_id','TEXT',1,NULL,0),
('catalogue_imports','source_filename','TEXT',0,NULL,0),
('catalogue_imports','mapping_json','TEXT',0,NULL,0),
('catalogue_imports','row_count','INTEGER',1,'0',0),
('catalogue_imports','created_count','INTEGER',1,'0',0),
('catalogue_imports','updated_count','INTEGER',1,'0',0),
('catalogue_imports','skipped_count','INTEGER',1,'0',0),
('catalogue_imports','imported_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('costing_lines','id','TEXT',0,NULL,1),
('costing_lines','job_id','INTEGER',1,NULL,0),
('costing_lines','option_id','TEXT',0,NULL,0),
('costing_lines','supplier_product_id','TEXT',0,NULL,0),
('costing_lines','supplier_name','TEXT',0,NULL,0),
('costing_lines','supplier_sku','TEXT',0,NULL,0),
('costing_lines','description','TEXT',1,NULL,0),
('costing_lines','unit_code','TEXT',0,NULL,0),
('costing_lines','quantity','REAL',1,'1',0),
('costing_lines','unit_cost','REAL',1,'0',0),
('costing_lines','markup_percent','REAL',1,'0',0),
('costing_lines','customer_unit_price','REAL',1,'0',0),
('costing_lines','category','TEXT',1,'''materials''',0),
('costing_lines','display_mode','TEXT',1,'''show''',0),
('costing_lines','combine_label','TEXT',0,NULL,0),
('costing_lines','sort_order','INTEGER',1,'0',0),
('costing_lines','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('costing_lines','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('costing_options','id','TEXT',0,NULL,1),
('costing_options','job_id','INTEGER',1,NULL,0),
('costing_options','name','TEXT',1,NULL,0),
('costing_options','status','TEXT',1,'''draft''',0),
('costing_options','default_markup_percent','REAL',1,'30',0),
('costing_options','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('costing_options','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('customer_invoice_versions','id','TEXT',0,NULL,1),
('customer_invoice_versions','job_id','INTEGER',1,NULL,0),
('customer_invoice_versions','version_number','INTEGER',1,NULL,0),
('customer_invoice_versions','status','TEXT',1,'''draft''',0),
('customer_invoice_versions','snapshot_json','TEXT',1,NULL,0),
('customer_invoice_versions','source_hash','TEXT',1,NULL,0),
('customer_invoice_versions','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('customer_invoice_versions','issued_at','TEXT',0,NULL,0),
('customer_invoice_versions','paid_at','TEXT',0,NULL,0),
('customer_invoice_versions','voided_at','TEXT',0,NULL,0),
('customer_quote_versions','id','TEXT',0,NULL,1),
('customer_quote_versions','job_id','INTEGER',1,NULL,0),
('customer_quote_versions','version_number','INTEGER',1,NULL,0),
('customer_quote_versions','status','TEXT',1,'''draft''',0),
('customer_quote_versions','snapshot_json','TEXT',1,NULL,0),
('customer_quote_versions','source_hash','TEXT',1,NULL,0),
('customer_quote_versions','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('customer_quote_versions','issued_at','TEXT',0,NULL,0),
('customer_quote_versions','accepted_at','TEXT',0,NULL,0),
('email_logs','id','TEXT',0,NULL,1),
('email_logs','job_id','INTEGER',1,NULL,0),
('email_logs','email_type','TEXT',1,NULL,0),
('email_logs','recipient','TEXT',1,NULL,0),
('email_logs','subject','TEXT',1,NULL,0),
('email_logs','provider_message_id','TEXT',0,NULL,0),
('email_logs','status','TEXT',1,NULL,0),
('email_logs','included_json','TEXT',0,NULL,0),
('email_logs','missing_json','TEXT',0,NULL,0),
('email_logs','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('enquiries','id','INTEGER',0,NULL,1),
('enquiries','enquiry_ref','TEXT',1,NULL,0),
('enquiries','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('enquiries','customer_name','TEXT',0,NULL,0),
('enquiries','email','TEXT',0,NULL,0),
('enquiries','phone','TEXT',0,NULL,0),
('enquiries','address','TEXT',0,NULL,0),
('enquiries','answers_json','TEXT',1,NULL,0),
('enquiries','summer_bill_file','TEXT',0,NULL,0),
('enquiries','winter_bill_file','TEXT',0,NULL,0),
('enquiries','opensolar_status','TEXT',1,'''not_created''',0),
('enquiries','opensolar_project_id','TEXT',0,NULL,0),
('enquiries','job_status','TEXT',1,'''enquiry''',0),
('enquiries','notes','TEXT',0,NULL,0),
('general_job_details','job_id','INTEGER',0,NULL,1),
('general_job_details','data_json','TEXT',1,NULL,0),
('general_job_details','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_files','id','TEXT',0,NULL,1),
('job_files','job_id','INTEGER',1,NULL,0),
('job_files','storage_key','TEXT',1,NULL,0),
('job_files','original_name','TEXT',1,NULL,0),
('job_files','content_type','TEXT',0,NULL,0),
('job_files','size_bytes','INTEGER',1,NULL,0),
('job_files','category','TEXT',1,NULL,0),
('job_files','caption','TEXT',0,NULL,0),
('job_files','uploaded_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_files','document_role','TEXT',0,NULL,0),
('job_files','energy_data_detail','TEXT',0,NULL,0),
('job_materials','id','TEXT',0,NULL,1),
('job_materials','job_id','INTEGER',1,NULL,0),
('job_materials','source','TEXT',1,'''supplier_invoice''',0),
('job_materials','supplier_name','TEXT',0,NULL,0),
('job_materials','invoice_number','TEXT',0,NULL,0),
('job_materials','invoice_date','TEXT',0,NULL,0),
('job_materials','invoice_file_id','TEXT',0,NULL,0),
('job_materials','description','TEXT',1,NULL,0),
('job_materials','supplier_sku','TEXT',0,NULL,0),
('job_materials','quantity','REAL',1,'1',0),
('job_materials','unit_code','TEXT',0,NULL,0),
('job_materials','unit_cost_ex_gst','REAL',1,'0',0),
('job_materials','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_materials','billable_to_customer','INTEGER',1,'1',0),
('job_materials','customer_markup_percent','REAL',1,'30',0),
('job_materials','material_status','TEXT',1,'''normal''',0),
('job_materials','supplier_invoice_inbox_id','TEXT',0,NULL,0),
('job_supplier_pricing','job_id','INTEGER',0,NULL,1),
('job_supplier_pricing','data_json','TEXT',1,NULL,0),
('job_supplier_pricing','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_work_logs','id','TEXT',0,NULL,1),
('job_work_logs','job_id','INTEGER',1,NULL,0),
('job_work_logs','work_date','TEXT',1,NULL,0),
('job_work_logs','hours','REAL',1,NULL,0),
('job_work_logs','supervisor','TEXT',0,NULL,0),
('job_work_logs','supervision_type','TEXT',1,NULL,0),
('job_work_logs','competency','TEXT',1,NULL,0),
('job_work_logs','work_completed','TEXT',1,NULL,0),
('job_work_logs','tests_results','TEXT',0,NULL,0),
('job_work_logs','issues_notes','TEXT',0,NULL,0),
('job_work_logs','supervisor_notes','TEXT',0,NULL,0),
('job_work_logs','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('job_work_logs','start_time','TEXT',0,NULL,0),
('job_work_logs','finish_time','TEXT',0,NULL,0),
('job_work_logs','materials_used','TEXT',0,NULL,0),
('job_work_logs','certification_status','TEXT',0,NULL,0),
('job_work_logs','work_dates','TEXT',0,NULL,0),
('job_work_logs','days','REAL',1,'1',0),
('jobs','id','INTEGER',0,NULL,1),
('jobs','enquiry_id','INTEGER',1,NULL,0),
('jobs','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('jobs','job_status','TEXT',1,'''new_enquiry''',0),
('jobs','next_action','TEXT',0,NULL,0),
('jobs','next_action_date','TEXT',0,NULL,0),
('jobs','assigned_to','TEXT',0,NULL,0),
('jobs','quote_amount','REAL',0,NULL,0),
('jobs','quote_status','TEXT',0,'''not_started''',0),
('jobs','accepted_at','TEXT',0,NULL,0),
('jobs','opensolar_project_id','TEXT',0,NULL,0),
('jobs','opensolar_project_url','TEXT',0,NULL,0),
('jobs','opensolar_status','TEXT',0,'''not_created''',0),
('jobs','system_size_kw','REAL',0,NULL,0),
('jobs','inverter','TEXT',0,NULL,0),
('jobs','battery','TEXT',0,NULL,0),
('jobs','proposal_value','REAL',0,NULL,0),
('jobs','proposal_sent_at','TEXT',0,NULL,0),
('jobs','icp','TEXT',0,NULL,0),
('jobs','vector_dg_status','TEXT',0,'''not_started''',0),
('jobs','vector_dg_submitted_at','TEXT',0,NULL,0),
('jobs','vector_dg_reference','TEXT',0,NULL,0),
('jobs','vector_dg_approved_at','TEXT',0,NULL,0),
('jobs','export_limit_kw','REAL',0,NULL,0),
('jobs','retailer','TEXT',0,NULL,0),
('jobs','retailer_plan','TEXT',0,NULL,0),
('jobs','import_rate_cents','REAL',0,NULL,0),
('jobs','export_rate_cents','REAL',0,NULL,0),
('jobs','daily_fixed_charge','REAL',0,NULL,0),
('jobs','tariff_check_status','TEXT',0,'''not_checked''',0),
('jobs','recommended_retailer','TEXT',0,NULL,0),
('jobs','recommended_plan','TEXT',0,NULL,0),
('jobs','retailer_status','TEXT',0,'''not_started''',0),
('jobs','retailer_contacted_at','TEXT',0,NULL,0),
('jobs','meter_status','TEXT',0,'''not_checked''',0),
('jobs','export_confirmed','INTEGER',0,'0',0),
('jobs','finance_type','TEXT',0,'''unknown''',0),
('jobs','finance_provider','TEXT',0,NULL,0),
('jobs','finance_status','TEXT',0,'''not_applicable''',0),
('jobs','deposit_required','REAL',0,NULL,0),
('jobs','deposit_status','TEXT',0,'''not_requested''',0),
('jobs','deposit_received','REAL',0,NULL,0),
('jobs','deposit_received_at','TEXT',0,NULL,0),
('jobs','materials_status','TEXT',0,'''not_ordered''',0),
('jobs','materials_cost','REAL',0,NULL,0),
('jobs','materials_ordered_at','TEXT',0,NULL,0),
('jobs','materials_received_at','TEXT',0,NULL,0),
('jobs','supplier','TEXT',0,NULL,0),
('jobs','install_status','TEXT',0,'''not_scheduled''',0),
('jobs','install_date','TEXT',0,NULL,0),
('jobs','install_completed_at','TEXT',0,NULL,0),
('jobs','trainee_hours','REAL',0,NULL,0),
('jobs','trainee_work_notes','TEXT',0,NULL,0),
('jobs','install_photos_status','TEXT',0,'''not_uploaded''',0),
('jobs','test_sheet_status','TEXT',0,'''not_completed''',0),
('jobs','supervisor','TEXT',0,'''Ben''',0),
('jobs','supervision_status','TEXT',0,'''not_started''',0),
('jobs','supervisor_approval_status','TEXT',0,'''not_approved''',0),
('jobs','inspection_status','TEXT',0,'''not_required''',0),
('jobs','inspector','TEXT',0,NULL,0),
('jobs','inspection_date','TEXT',0,NULL,0),
('jobs','coc_status','TEXT',0,'''not_issued''',0),
('jobs','coc_number','TEXT',0,NULL,0),
('jobs','coc_issued_at','TEXT',0,NULL,0),
('jobs','final_payment_status','TEXT',0,'''not_due''',0),
('jobs','final_payment_received_at','TEXT',0,NULL,0),
('jobs','job_type','TEXT',1,'''solar''',0),
('jobs','supplier_reference','TEXT',0,NULL,0),
('site_visits','job_id','INTEGER',0,NULL,1),
('site_visits','data_json','TEXT',1,NULL,0),
('site_visits','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('supplier_products','id','TEXT',0,NULL,1),
('supplier_products','supplier_id','TEXT',1,NULL,0),
('supplier_products','supplier_sku','TEXT',1,NULL,0),
('supplier_products','description','TEXT',1,NULL,0),
('supplier_products','unit_code','TEXT',0,NULL,0),
('supplier_products','category_code','TEXT',0,NULL,0),
('supplier_products','barcode','TEXT',0,NULL,0),
('supplier_products','list_price','REAL',0,NULL,0),
('supplier_products','buy_price','REAL',0,NULL,0),
('supplier_products','gst_treatment','TEXT',1,'''exclusive''',0),
('supplier_products','brand','TEXT',0,NULL,0),
('supplier_products','manufacturer_sku','TEXT',0,NULL,0),
('supplier_products','price_class','TEXT',0,NULL,0),
('supplier_products','source_price_date','TEXT',0,NULL,0),
('supplier_products','last_imported_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('supplier_products','active','INTEGER',1,'1',0),
('suppliers','id','TEXT',0,NULL,1),
('suppliers','name','TEXT',1,NULL,0),
('suppliers','active','INTEGER',1,'1',0),
('suppliers','created_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('suppliers','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0),
('suppliers','is_default','INTEGER',1,'0',0),
('system_designs','job_id','INTEGER',0,NULL,1),
('system_designs','data_json','TEXT',1,NULL,0),
('system_designs','updated_at','TEXT',1,'CURRENT_TIMESTAMP',0)
),
expected_indexes(name, table_name, unique_flag, partial_flag) AS (VALUES
('idx_bk_audit_entity','bookkeeping_audit_events',0,0),
('idx_bk_bank_feed_queue','bookkeeping_bank_feed_transactions',0,0),
('idx_bk_bank_feed_reference','bookkeeping_bank_feed_transactions',0,0),
('idx_bk_journal_lines_account','bookkeeping_journal_lines',0,0),
('idx_bk_journals_book_date','bookkeeping_journals',0,0),
('idx_bk_reconciliation_matches_target','bookkeeping_reconciliation_matches',0,0),
('idx_bk_reconciliation_queue','bookkeeping_reconciliation_reviews',0,0),
('idx_bk_tax_events_book_type_date','bookkeeping_tax_events',0,0),
('idx_bk_transactions_book_date','bookkeeping_transactions',0,0),
('idx_bk_transactions_contact_due','bookkeeping_transactions',0,0),
('idx_bk_transactions_job','bookkeeping_transactions',0,0),
('idx_catalogue_imports_supplier','catalogue_imports',0,0),
('idx_costing_lines_job_option','costing_lines',0,0),
('idx_costing_options_job','costing_options',0,0),
('idx_customer_invoices_job_version','customer_invoice_versions',0,0),
('idx_customer_quotes_job_version','customer_quote_versions',0,0),
('idx_enquiries_created_at','enquiries',0,0),
('idx_enquiries_email','enquiries',0,0),
('idx_job_materials_job','job_materials',0,0),
('idx_job_materials_supplier_inbox','job_materials',1,1),
('idx_jobs_supplier_reference_unique','jobs',1,1),
('idx_supplier_invoice_inbox_book_status','bookkeeping_supplier_invoice_inbox',0,0),
('idx_supplier_invoice_inbox_hash','bookkeeping_supplier_invoice_inbox',0,0),
('idx_supplier_invoice_inbox_job','bookkeeping_supplier_invoice_inbox',0,0),
('idx_supplier_invoice_inbox_number','bookkeeping_supplier_invoice_inbox',0,0),
('idx_supplier_products_description','supplier_products',0,0),
('idx_supplier_products_sku','supplier_products',0,0)
),
expected_index_columns(index_name, seqno, column_name) AS (VALUES
('idx_bk_audit_entity',0,'book_id'),
('idx_bk_audit_entity',1,'entity_type'),
('idx_bk_audit_entity',2,'entity_id'),
('idx_bk_audit_entity',3,'event_at'),
('idx_bk_bank_feed_queue',0,'book_id'),
('idx_bk_bank_feed_queue',1,'transaction_status'),
('idx_bk_bank_feed_queue',2,'transaction_date'),
('idx_bk_bank_feed_reference',0,'book_id'),
('idx_bk_bank_feed_reference',1,'reference'),
('idx_bk_bank_feed_reference',2,'amount'),
('idx_bk_journal_lines_account',0,'account_id'),
('idx_bk_journal_lines_account',1,'journal_id'),
('idx_bk_journals_book_date',0,'book_id'),
('idx_bk_journals_book_date',1,'journal_date'),
('idx_bk_journals_book_date',2,'posted'),
('idx_bk_reconciliation_matches_target',0,'book_id'),
('idx_bk_reconciliation_matches_target',1,'target_transaction_id'),
('idx_bk_reconciliation_queue',0,'book_id'),
('idx_bk_reconciliation_queue',1,'review_status'),
('idx_bk_reconciliation_queue',2,'created_at'),
('idx_bk_tax_events_book_type_date',0,'book_id'),
('idx_bk_tax_events_book_type_date',1,'tax_type'),
('idx_bk_tax_events_book_type_date',2,'event_date'),
('idx_bk_transactions_book_date',0,'book_id'),
('idx_bk_transactions_book_date',1,'transaction_date'),
('idx_bk_transactions_book_date',2,'kind'),
('idx_bk_transactions_contact_due',0,'book_id'),
('idx_bk_transactions_contact_due',1,'contact_name'),
('idx_bk_transactions_contact_due',2,'due_date'),
('idx_bk_transactions_job',0,'book_id'),
('idx_bk_transactions_job',1,'job_id'),
('idx_bk_transactions_job',2,'transaction_date'),
('idx_catalogue_imports_supplier',0,'supplier_id'),
('idx_catalogue_imports_supplier',1,'imported_at'),
('idx_costing_lines_job_option',0,'job_id'),
('idx_costing_lines_job_option',1,'option_id'),
('idx_costing_lines_job_option',2,'sort_order'),
('idx_costing_options_job',0,'job_id'),
('idx_costing_options_job',1,'created_at'),
('idx_customer_invoices_job_version',0,'job_id'),
('idx_customer_invoices_job_version',1,'version_number'),
('idx_customer_quotes_job_version',0,'job_id'),
('idx_customer_quotes_job_version',1,'version_number'),
('idx_enquiries_created_at',0,'created_at'),
('idx_enquiries_email',0,'email'),
('idx_job_materials_job',0,'job_id'),
('idx_job_materials_job',1,'created_at'),
('idx_job_materials_supplier_inbox',0,'supplier_invoice_inbox_id'),
('idx_jobs_supplier_reference_unique',0,'supplier_reference'),
('idx_supplier_invoice_inbox_book_status',0,'book_id'),
('idx_supplier_invoice_inbox_book_status',1,'matching_status'),
('idx_supplier_invoice_inbox_book_status',2,'received_at'),
('idx_supplier_invoice_inbox_hash',0,'book_id'),
('idx_supplier_invoice_inbox_hash',1,'content_sha256'),
('idx_supplier_invoice_inbox_job',0,'book_id'),
('idx_supplier_invoice_inbox_job',1,'job_id'),
('idx_supplier_invoice_inbox_job',2,'supplier_invoice_date'),
('idx_supplier_invoice_inbox_number',0,'book_id'),
('idx_supplier_invoice_inbox_number',1,'supplier_name'),
('idx_supplier_invoice_inbox_number',2,'supplier_invoice_number'),
('idx_supplier_products_description',0,'description'),
('idx_supplier_products_sku',0,'supplier_sku')
),
expected_foreign_keys(source_table, source_column, target_table, target_column, on_update, on_delete) AS (VALUES
('bookkeeping_accounts','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_audit_events','transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_audit_events','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_accounts','ledger_account_id','bookkeeping_accounts','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_accounts','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_audit','bank_transaction_id','bookkeeping_bank_feed_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_audit','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_imports','bank_account_id','bookkeeping_bank_accounts','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_imports','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_transactions','import_id','bookkeeping_bank_feed_imports','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_transactions','bank_account_id','bookkeeping_bank_accounts','id','NO ACTION','NO ACTION'),
('bookkeeping_bank_feed_transactions','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_document_links','transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_document_links','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_export_mappings','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_fixed_assets','transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_fixed_assets','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_job_books','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_journal_lines','account_id','bookkeeping_accounts','id','NO ACTION','NO ACTION'),
('bookkeeping_journal_lines','journal_id','bookkeeping_journals','id','NO ACTION','NO ACTION'),
('bookkeeping_journals','reversed_by','bookkeeping_journals','id','NO ACTION','NO ACTION'),
('bookkeeping_journals','transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_journals','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_opening_balances','account_id','bookkeeping_accounts','id','NO ACTION','NO ACTION'),
('bookkeeping_opening_balances','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_payment_allocations','invoice_transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_payment_allocations','payment_transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_payment_allocations','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_matches','target_transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_matches','payment_transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_matches','bank_transaction_id','bookkeeping_bank_feed_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_matches','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_reviews','selected_transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_reviews','bank_transaction_id','bookkeeping_bank_feed_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_reconciliation_reviews','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_supplier_inbox_addresses','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_supplier_invoice_events','inbox_id','bookkeeping_supplier_invoice_inbox','id','NO ACTION','NO ACTION'),
('bookkeeping_supplier_invoice_events','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_supplier_invoice_inbox','accounting_transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_supplier_invoice_inbox','duplicate_of_id','bookkeeping_supplier_invoice_inbox','id','NO ACTION','NO ACTION'),
('bookkeeping_supplier_invoice_inbox','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_tax_accounts','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_tax_adjustments','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_tax_events','transaction_id','bookkeeping_transactions','id','NO ACTION','NO ACTION'),
('bookkeeping_tax_events','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('bookkeeping_transactions','account_id','bookkeeping_accounts','id','NO ACTION','NO ACTION'),
('bookkeeping_transactions','book_id','bookkeeping_books','id','NO ACTION','NO ACTION'),
('catalogue_imports','supplier_id','suppliers','id','NO ACTION','NO ACTION'),
('costing_lines','supplier_product_id','supplier_products','id','NO ACTION','NO ACTION'),
('costing_lines','option_id','costing_options','id','NO ACTION','NO ACTION'),
('jobs','enquiry_id','enquiries','id','NO ACTION','NO ACTION'),
('supplier_products','supplier_id','suppliers','id','NO ACTION','NO ACTION')
),
actual_tables(name) AS (
  SELECT name FROM sqlite_schema
  WHERE type='table' AND sql IS NOT NULL
    AND name NOT LIKE 'sqlite_%' AND substr(name,1,4) <> '_cf_'
    AND name <> 'd1_migrations'
),
actual_columns(table_name, column_name, column_type, notnull_flag, default_value, pk) AS (
  SELECT s.name, p.name, upper(coalesce(p.type,'')), p."notnull", p.dflt_value, p.pk
  FROM sqlite_schema AS s JOIN pragma_table_info(s.name) AS p
  WHERE s.type='table' AND s.sql IS NOT NULL
    AND s.name NOT LIKE 'sqlite_%' AND substr(s.name,1,4) <> '_cf_'
    AND s.name <> 'd1_migrations'
),
actual_indexes(name, table_name, unique_flag, partial_flag) AS (
  SELECT s.name, s.tbl_name,
    (SELECT il."unique" FROM pragma_index_list(s.tbl_name) AS il WHERE il.name=s.name),
    (SELECT il.partial FROM pragma_index_list(s.tbl_name) AS il WHERE il.name=s.name)
  FROM sqlite_schema AS s
  WHERE s.type='index' AND s.sql IS NOT NULL
    AND s.name NOT LIKE 'sqlite_%' AND substr(s.name,1,4) <> '_cf_'
),
actual_index_columns(index_name, seqno, column_name) AS (
  SELECT s.name, ii.seqno, ii.name
  FROM sqlite_schema AS s JOIN pragma_index_info(s.name) AS ii
  WHERE s.type='index' AND s.sql IS NOT NULL
    AND s.name NOT LIKE 'sqlite_%' AND substr(s.name,1,4) <> '_cf_'
),
actual_foreign_keys(source_table, source_column, target_table, target_column, on_update, on_delete) AS (
  SELECT s.name, fk."from", fk."table", fk."to", upper(fk.on_update), upper(fk.on_delete)
  FROM sqlite_schema AS s JOIN pragma_foreign_key_list(s.name) AS fk
  WHERE s.type='table' AND s.sql IS NOT NULL
    AND s.name NOT LIKE 'sqlite_%' AND substr(s.name,1,4) <> '_cf_'
    AND s.name <> 'd1_migrations'
),
problems(issue) AS (
  SELECT 'TABLE_COUNT expected=42 actual='||(SELECT count(*) FROM actual_tables)
    WHERE (SELECT count(*) FROM actual_tables) <> 42
  UNION ALL
  SELECT 'INDEX_COUNT expected=27 actual='||(SELECT count(*) FROM actual_indexes)
    WHERE (SELECT count(*) FROM actual_indexes) <> 27
  UNION ALL
  SELECT 'MISSING_TABLE:'||e.name FROM expected_tables e
    WHERE NOT EXISTS (SELECT 1 FROM actual_tables a WHERE a.name=e.name)
  UNION ALL
  SELECT 'UNEXPECTED_TABLE:'||a.name FROM actual_tables a
    WHERE NOT EXISTS (SELECT 1 FROM expected_tables e WHERE e.name=a.name)
  UNION ALL
  SELECT 'MISSING_OR_MISMATCHED_COLUMN:'||e.table_name||'.'||e.column_name
    FROM expected_columns e WHERE NOT EXISTS (
      SELECT 1 FROM actual_columns a WHERE a.table_name=e.table_name AND a.column_name=e.column_name
        AND upper(a.column_type)=e.column_type AND a.notnull_flag=e.notnull_flag
        AND a.default_value IS e.default_value AND a.pk=e.pk
    )
  UNION ALL
  SELECT 'UNEXPECTED_COLUMN:'||a.table_name||'.'||a.column_name
    FROM actual_columns a WHERE NOT EXISTS (
      SELECT 1 FROM expected_columns e WHERE e.table_name=a.table_name AND e.column_name=a.column_name
    )
  UNION ALL
  SELECT 'MISSING_OR_MISMATCHED_INDEX:'||e.name FROM expected_indexes e WHERE NOT EXISTS (
    SELECT 1 FROM actual_indexes a WHERE a.name=e.name AND a.table_name=e.table_name
      AND a.unique_flag=e.unique_flag AND a.partial_flag=e.partial_flag
  )
  UNION ALL
  SELECT 'UNEXPECTED_INDEX:'||a.name FROM actual_indexes a WHERE NOT EXISTS (
    SELECT 1 FROM expected_indexes e WHERE e.name=a.name AND e.table_name=a.table_name
  )
  UNION ALL
  SELECT 'MISSING_INDEX_COLUMN:'||e.index_name||'['||e.seqno||']'
    FROM expected_index_columns e WHERE NOT EXISTS (
      SELECT 1 FROM actual_index_columns a WHERE a.index_name=e.index_name
        AND a.seqno=e.seqno AND a.column_name IS e.column_name
    )
  UNION ALL
  SELECT 'UNEXPECTED_INDEX_COLUMN:'||a.index_name||'['||a.seqno||']'
    FROM actual_index_columns a WHERE NOT EXISTS (
      SELECT 1 FROM expected_index_columns e WHERE e.index_name=a.index_name
        AND e.seqno=a.seqno AND e.column_name IS a.column_name
    )
  UNION ALL
  SELECT 'MISSING_FOREIGN_KEY:'||e.source_table||'.'||e.source_column||'->'||e.target_table||'.'||e.target_column
    FROM expected_foreign_keys e WHERE NOT EXISTS (
      SELECT 1 FROM actual_foreign_keys a WHERE a.source_table=e.source_table
        AND a.source_column=e.source_column AND a.target_table=e.target_table
        AND a.target_column=e.target_column AND a.on_update=e.on_update AND a.on_delete=e.on_delete
    )
  UNION ALL
  SELECT 'UNEXPECTED_FOREIGN_KEY:'||a.source_table||'.'||a.source_column||'->'||a.target_table||'.'||a.target_column
    FROM actual_foreign_keys a WHERE NOT EXISTS (
      SELECT 1 FROM expected_foreign_keys e WHERE e.source_table=a.source_table
        AND e.source_column=a.source_column AND e.target_table=a.target_table
        AND e.target_column=a.target_column AND e.on_update=a.on_update AND e.on_delete=a.on_delete
    )
  UNION ALL
  SELECT 'INTEGRITY_CHECK_FAILED:'||integrity_check
    FROM pragma_integrity_check WHERE integrity_check <> 'ok'
  UNION ALL
  SELECT 'FOREIGN_KEY_VIOLATION:'||"table"||':'||coalesce(cast("rowid" AS TEXT),'NULL')||':'||"parent"
    FROM pragma_foreign_key_check
)
SELECT 'JOBHUB_SCHEMA_VERIFY_OK' AS result
WHERE NOT EXISTS (SELECT 1 FROM problems)
UNION ALL
SELECT issue FROM problems
ORDER BY 1;
